src/classifier.js
src/config.js

Multi intent detection is not desirable for most bots.

Add multiIntent config param, defaults to false

---

packages/botfuel-dialog/src/nlu.js

Connected to https://app.asana.com/0/370953015396593/545440258872796

fix: Give context to intent filter when no QnA

---

packages/botfuel-dialog/src/config.js
packages/botfuel-dialog/tests/config/config.test.js

- add conversationDuration to default configuration
- fix arbitrary configuration
- add tests

Conversation duration in configuration

---

packages/botfuel-dialog/src/adapters/adapter.js
packages/botfuel-dialog/src/dialogs/dialog.js
packages/botfuel-dialog/src/middleware-manager.js
packages/test-middlewares/tests/out-middleware.test.js

fix: Expose user message in out middleware context
fix: Fix out middleware issue with done function

Fix middlewares

---

packages/botfuel-dialog/src/brains/memory-brain.js
packages/botfuel-dialog/src/brains/mongo-brain.js

Will provide `User does not exist` error instead of `TypeError: Cannot read property 'conversations' of undefined`

Make userId reliant functions throw when user does not exist

---

packages/botfuel-dialog/src/bot.js
packages/botfuel-dialog/src/dialogs/prompt-dialog.js
packages/botfuel-dialog/src/nlu.js
packages/test-middlewares/src/middlewares.js

Also fixed style in several places.

Refactored how spellchecking is called

---

packages/botfuel-dialog/src/adapters/shell-adapter.js
packages/botfuel-dialog/src/run.js

Fix shell adapter

---

.eslintrc
packages/botfuel-dialog/src/adapters/shell-adapter.js
packages/botfuel-dialog/src/brains/memory-brain.js
packages/botfuel-dialog/src/brains/mongo-brain.js
packages/botfuel-dialog/tests/adapters/adapter.test.js
packages/botfuel-dialog/tests/adapters/web-adapter.test.js
packages/botfuel-dialog/tests/brains/brains.test.js
packages/botfuel-dialog/tests/dialogs/dialog.test.js
packages/botfuel-dialog/tests/extractors/extractor.test.js
packages/botfuel-dialog/tests/extractors/ws-extractor.test.js

- fixed tests
- ensure uniqueness of `_userId` in brains when adding user

brainoptim fixes

---

CONTRIBUTING.md
packages/botfuel-dialog/src/adapters/botfuel-adapter.js
packages/botfuel-dialog/src/adapters/messenger-adapter.js
packages/botfuel-dialog/src/adapters/shell-adapter.js
packages/botfuel-dialog/src/adapters/web-adapter.js
packages/botfuel-dialog/tests/adapters/botfuel-adapter.test.js
packages/botfuel-dialog/tests/adapters/messenger-adapter.test.js
packages/botfuel-dialog/tests/adapters/shell-adapter.test.js

Asana: https://app.asana.com/0/481142309329793/509399402509027
This goes with https://github.com/Botfuel/botfuel-docs/pull/27

Document adapters

---

CONTRIBUTING.md
README.md

https://app.asana.com/0/481142309329793/575508152340275

Improve code guidelines

---

packages/botfuel-dialog/src/adapters/web-adapter.js

fix: set quality of image screenshot default value to 80

---

packages/botfuel-dialog/src/bot.js
packages/botfuel-dialog/src/config.js
packages/botfuel-dialog/src/dialog-manager.js
packages/botfuel-dialog/src/dialogs/classification-disambiguation-dialog.js
packages/botfuel-dialog/src/nlus/botfuel-nlu.js
packages/botfuel-dialog/src/nlus/botfuel-trainer-nlu.js
packages/botfuel-dialog/src/nlus/classification-result.js
packages/botfuel-dialog/src/views/classification-disambiguation-view.js
packages/botfuel-dialog/tests/dialog-manager/dialog-manager.test.js
packages/botfuel-dialog/tests/dialogs/classification-disambiguation-dialog.test.js
packages/botfuel-dialog/tests/nlus/botfuel-trainer-nlu.test.js
packages/botfuel-dialog/tests/nlus/classification-result.test.js
packages/botfuel-dialog/tests/views/classification-disambiguation-view.test.js

- remove trainer api url in the config
- rename resolution dialog to disambiguation dialog
- rename intent class to classification result class

refactor: trainer nlu code optimization

---

packages/botfuel-dialog/src/adapters/adapter.js
packages/botfuel-dialog/src/adapters/messenger-adapter.js
packages/botfuel-dialog/src/bot.js
packages/botfuel-dialog/src/dialog-manager.js
packages/botfuel-dialog/src/dialogs/base-dialog.js
packages/botfuel-dialog/src/dialogs/dialog.js
packages/botfuel-dialog/src/dialogs/prompt-dialog.js
packages/botfuel-dialog/src/dialogs/void-dialog.js
packages/botfuel-dialog/tests/dialog-manager/dialog-manager.test.js
packages/botfuel-dialog/tests/dialog-manager/src/dialogs/waiting-dialog.js
packages/botfuel-dialog/tests/dialogs/classification-disambiguation-dialog.test.js
packages/botfuel-dialog/tests/dialogs/confirmation-dialog.test.js
packages/botfuel-dialog/tests/dialogs/dialog.test.js
packages/botfuel-dialog/tests/dialogs/prompt-dialog.test.js
packages/botfuel-dialog/tests/dialogs/qnas-dialog.test.js
packages/botfuel-dialog/tests/dialogs/void-dialog.test.js
yarn.lock

Connected to https://app.asana.com/0/481142309329793/629369582471433

Refactor message passing

---

packages/botfuel-dialog/src/config.js
packages/test-modules/test-config.js
packages/test-qna/botfuel-config.js
packages/test-qna/shell-config.js
packages/test-qna/test-config.js
packages/test-resolvers/test-config.js

use lodash merge to merge deep object

fix: fix merge config to default config

---

packages/sample-botfuel-module/.eslintrc
packages/sample-botfuel-module/LICENSE.md
packages/sample-botfuel-module/README.md
packages/sample-botfuel-module/index.js
packages/sample-botfuel-module/package.json
packages/sample-botfuel-module/src/adapters/sample-module-adapter.js
packages/sample-botfuel-module/src/brains/sample-module-brain.js
packages/sample-botfuel-module/src/dialogs/sample-abstract-module-dialog.js
packages/sample-botfuel-module/src/dialogs/sample-concrete-module-dialog.js
packages/sample-botfuel-module/src/nlus/sample-module-nlu.js
packages/sample-botfuel-module/src/views/sample-abstract-module-view.js
packages/sample-botfuel-module/src/views/sample-concrete-module-view.js
packages/sample-botfuel-module/tests/adapters/sample-module-adapter.test.js
packages/sample-botfuel-module/tests/brains/sample-module-brain.test.js
packages/sample-botfuel-module/tests/dialogs/sample-abstract-module-dialog.test.js
packages/sample-botfuel-module/tests/dialogs/sample-concrete-module-dialog.test.js
packages/sample-botfuel-module/tests/nlus/sample-module-nlu.test.js
packages/sample-botfuel-module/tests/views/sample-abstract-module-view.test.js
packages/sample-botfuel-module/tests/views/sample-concrete-module-view.test.js
packages/test-modules/package.json
yarn.lock

See https://app.asana.com/0/370953015396593/639638765947419

chore: Mode the sample module to the monorepo

---

CHANGELOG.md
packages/botfuel-dialog/src/adapters/messenger-adapter.js

See FB doc: https://developers.facebook.com/docs/messenger-platform/send-messages
See task: https://app.asana.com/0/481142309329793/654091769954838

Add field messaging_type in FB responses

---

packages/botfuel-dialog/src/adapters/shell-adapter.js

Sometimes it is useful to handle actions message in shell for development purpose (no need to setup webchat...)
==> bot proposes choices for action

feat: support actions message in shell adapter

---

.flowconfig
CONTRIBUTING.md
packages/botfuel-dialog/src/adapter-resolver.js
packages/botfuel-dialog/src/adapters/adapter.js
packages/botfuel-dialog/src/adapters/messenger-adapter.js
packages/botfuel-dialog/src/bot.js
packages/botfuel-dialog/src/brain-resolver.js
packages/botfuel-dialog/src/brains/brain.js
packages/botfuel-dialog/src/classifier.js
packages/botfuel-dialog/src/config.js
packages/botfuel-dialog/src/dialog-manager.js
packages/botfuel-dialog/src/dialogs/dialog.js
packages/botfuel-dialog/src/messages/message.js
packages/botfuel-dialog/src/messages/valid-object.js
packages/botfuel-dialog/src/middleware-manager.js
packages/botfuel-dialog/src/nlu-resolver.js
packages/botfuel-dialog/src/nlus/classification-result.js
packages/botfuel-dialog/src/nlus/nlu.js
packages/botfuel-dialog/src/resolver.js
packages/botfuel-dialog/src/types.js
packages/botfuel-dialog/src/view-resolver.js
packages/botfuel-dialog/src/views/view.js
packages/botfuel-dialog/tests/adapters/adapter.test.js
packages/botfuel-dialog/tests/adapters/botfuel-adapter.test.js
packages/botfuel-dialog/tests/adapters/messenger-adapter.test.js
packages/botfuel-dialog/tests/adapters/shell-adapter.test.js
packages/botfuel-dialog/tests/dialogs/dialog.test.js

See https://app.asana.com/0/370953015396593/639638765947422
Flow has still a lot of bugs with exact types. They should be used only when necessary.
For vscode, I use the extentions dbaeumer.vscode-eslint, flowtype.flow-for-vscode, joshpeng.sublime-babel-vscode.
Disable js validation:
```
cat .vscode/settings.json
{
"javascript.validate.enable": false
}
```

Play with facebook flow

---

CONTRIBUTING.md

Connected to https://app.asana.com/0/481142309329793/658889505460732
Since this changes contributing rules, I think everybody should approve this PR.

docs: Add contributing rules for major versions

---

packages/botfuel-dialog/src/dialog-manager.js
packages/botfuel-dialog/tests/dialog-manager/dialog-manager.test.js

We need to resolve the state "not understood" of the bot after dialog and errors when we duplicate intents.

error behavior prompt intent

---

packages/botfuel-dialog/tests/extractors/boolean-extractor.test.js
packages/botfuel-dialog/tests/extractors/composite-extractor.test.js
packages/botfuel-dialog/tests/extractors/corpus-extractor.test.js
packages/botfuel-dialog/tests/extractors/location-extractor.test.js
packages/botfuel-dialog/tests/extractors/regex-extractor.test.js
packages/botfuel-dialog/tests/extractors/ws-extractor.test.js
packages/test-complexdialogs/tests/disgressions.test.js
packages/test-complexdialogs/tests/name.test.js
packages/test-complexdialogs/tests/travel.test.js

Replace expect(var.body).toBe(...) to expect(var.value).toBe(...)
task Asana: https://app.asana.com/0/481142309329793/714031389925389

chore: transform body to value in test

---

packages/botfuel-dialog/src/dialogs/complex-input-dialog.js
packages/botfuel-dialog/src/views/complex-input-view.js

task asana : https://app.asana.com/0/481142309329793/713832145048486

chore: change docs and classe's name

---

packages/botfuel-dialog/src/config.js
yarn.lock

As a bot developer I want to be able to add extra configuration under a `custom` key in the config file

Add key 'custom' to config whitelist

---

fixtures/api.botfuel.io-443/153078358788682509
fixtures/api.botfuel.io-443/153078358841443513
fixtures/api.botfuel.io-443/153078358867497990
fixtures/api.botfuel.io-443/153078358884065134
fixtures/api.botfuel.io-443/153078358904714805
fixtures/api.botfuel.io-443/153078358942468204
fixtures/api.botfuel.io-443/15307851052164164
fixtures/api.botfuel.io-443/153078510576230023
fixtures/api.botfuel.io-443/153078510600594091
fixtures/api.botfuel.io-443/153078510616954112
fixtures/api.botfuel.io-443/153078510638631828
fixtures/api.botfuel.io-443/153078510664861302
fixtures/api.botfuel.io-443/153078532595844343
fixtures/api.botfuel.io-443/153078532653692988
fixtures/api.botfuel.io-443/153078532678515613
fixtures/api.botfuel.io-443/153078532695075070
fixtures/api.botfuel.io-443/15307853272538565
fixtures/api.botfuel.io-443/153078532753064872
packages/botfuel-dialog/src/nlus/botfuel-nlu.js
packages/test-complexdialogs/package.json
packages/test-complexdialogs/src/dialogs/disanbiguationone-dialog.js
packages/test-complexdialogs/src/dialogs/disanbiguationtwo-dialog.js
packages/test-complexdialogs/src/intent-filter.js
packages/test-complexdialogs/src/views/disanbiguation-one-view.en.js
packages/test-complexdialogs/src/views/disanbiguation-two-view.en.js
packages/test-complexdialogs/tests/intent-filter.test.js

Add the filter intent which disappear since v8.

fix: add filter intent

---

packages/botfuel-dialog/src/index.js
packages/botfuel-dialog/src/nlus/botfuel-nlu.js

Rename "intent-filter" to "classification-filter".
Also, export ClassificationResult so the classif
filter can instanciate new ClassificationResults.

fix: In classif filter, filter both qnas and intents

---

CHANGELOG.md

add breaking change in changelog for this task: https://app.asana.com/0/481142309329793/525510224809560

chore: add breaking change in the changelog

---

packages/botfuel-dialog/src/bot.js
packages/botfuel-dialog/src/dialog-manager.js
packages/botfuel-dialog/src/messages/postback-message.js
packages/botfuel-dialog/src/messages/postback.js
packages/botfuel-dialog/src/types.js
packages/botfuel-dialog/src/views/classification-disambiguation-view.js
packages/botfuel-dialog/tests/messages/cards-message.test.js
packages/botfuel-dialog/tests/messages/postback-message.test.js
packages/botfuel-dialog/tests/views/classification-disambiguation-view.test.js
packages/botfuel-dialog/tests/views/qnas-view.test.js
packages/test-ecommerce/src/views/products-view.en.js
packages/test-ecommerce/tests/products.test.js
packages/test-qna/tests/qna.test.js

task asana: https://app.asana.com/0/481142309329793/714150271294805
Breaking change !

use postback with flexible manner

---

packages/botfuel-dialog/src/corpora/boolean.pt_br.txt
packages/botfuel-dialog/tests/extractors/boolean-extractor.test.js

task asana : https://app.asana.com/0/481142309329793/744886339991179

add bresilian portuguese in the sdk

---

packages/botfuel-dialog/src/bot.js
packages/botfuel-dialog/tests/dialogs/complex-input-dialog.test.js

- added check for input length on user text messages
- trigger **complex-input** dialog when input is > 256 characters
- added test for this fix
This will resolve https://github.com/Botfuel/botfuel-dialog/issues/226

fix: handle input too long

---

packages/botfuel-dialog/package.json
packages/botfuel-dialog/src/bot.js
packages/botfuel-dialog/src/nlus/botfuel-nlu.js
packages/botfuel-dialog/src/utils/measure.js
yarn.lock

feat: Measure response time of nlu & nlu steps

---

packages/botfuel-dialog/src/messages/card.js

Used for exemple in Messenger format : https://developers.facebook.com/docs/messenger-platform/send-messages/template/generic

feat: Add optional subtitle to Card constructor

---

packages/botfuel-dialog/src/brains/mongo-brain.js

fix: MongoBrain - return minimal amount of information to avoid network congestion
Add a projection in every findOne and findOneAndUpdate calls

fix: MongoBrain - return minimal amount of information from mongo

---

packages/botfuel-dialog/src/index.js
packages/botfuel-dialog/src/messages/hook.js

Add hook message type to complete Kevin's PR (https://github.com/Botfuel/botfuel-webchat-client/pull/41)

feat: add hook message type
