src/bot.js, src/brains/brain.js, src/brains/memory-brain.js, src/brains/mongo-brain.js, src/messages/message.js, src/views/view.js, tests/brains/brains.test.js, tests/messages/bot-text-message.test.js, tests/messages/cards-message.test.js, tests/messages/user-text-message.test.js
Some choices I made (tell me if you agree or not):
- Since `botId` is not needed anywhere but for botfuel webchat now, I completely removed it from the code
- You need to provide either `MONGODB_URI` or `BOTFUEL_APP_TOKEN` to use the mongo brain
=> Remove bot id + implement get/set methods in brain

CHANGELOG.md, lerna.json, package.json, packages/botfuel-dialog/CHANGELOG.md, packages/botfuel-dialog/package.json, packages/test-complexdialogs/.gitignore, packages/test-complexdialogs/package.json, packages/test-complexentities/.gitignore, packages/test-complexentities/package.json, packages/test-ecommerce/.gitignore, packages/test-ecommerce/package.json, packages/test-qna/.gitignore, packages/test-qna/package.json
Process:
- Write commit messages following https://conventionalcommits.org
- Make a PR
- Merge PR
- Release (using `yarn release`) when needed, this will automatically add new content to CHANGELOG.md (we can still edit CHANGELOG.md by hand, changes won't be overriden)
I chose the angular preset (default lerna preset):
If the prefix is feat, fix or perf, it will appear in the changelog. However if there is any BREAKING CHANGE, the commit will always appear in the changelog.
- `fix: Fix hello function` => Patch bump
- `feat: Add new functionality` => Minor bump
- `perf: Improve performance of hello function` => not sure if patch bump or no bump
- If there is `BREAKING CHANGE` in the commit message => Major bump
Other prefixes that don't update changelog: automatically:
- docs
- chore 
- …
=> Add changelog command

packages/botfuel-dialog/src/classifier.js, packages/botfuel-dialog/tests/classifier/classifier.test.js
When cloning a repo, the timestamps are regenerated so we cannot tell if the model is up to date based on them (in production especially).
So I propose we hash all intents content in a `models/.metadata` file and compare hashes.
I tried to unit test this but it seems very hard to do without consequent rewriting.
=> fix: Compare intents hashes instead of timestamps

packages/botfuel-dialog/src/views/prompt-view.js, packages/botfuel-dialog/tests/views/prompt-view.test.js
prompt view must send question for highest priority entity first since the entity are matched based on (dimension + priority order). This only impact the case where some entities have same dimension but different priority (before we can ask for one entity but match other entity)
=> fix: send question for entity with highest priority first in prompt-view

packages/botfuel-dialog/src/bot.js, packages/botfuel-dialog/src/dialog-manager.js, packages/botfuel-dialog/src/dialogs/confirmation-dialog.js, packages/botfuel-dialog/src/dialogs/dialog.js, packages/botfuel-dialog/src/dialogs/intent-resolution-dialog.js, packages/botfuel-dialog/src/dialogs/prompt-dialog.js, packages/botfuel-dialog/src/dialogs/qnas-dialog.js, packages/botfuel-dialog/src/dialogs/text-dialog.js, packages/botfuel-dialog/src/dialogs/void-dialog.js, packages/botfuel-dialog/src/views/confirmation-view.js, packages/botfuel-dialog/src/views/intent-resolution-view.js, packages/botfuel-dialog/src/views/prompt-view.js, packages/botfuel-dialog/src/views/qnas-view.js, packages/botfuel-dialog/tests/dialogs/dialog.test.js, packages/botfuel-dialog/tests/dialogs/intent-resolution-dialog.test.js, packages/botfuel-dialog/tests/dialogs/qnas-dialog.test.js, packages/botfuel-dialog/tests/views/confirmation-view.test.js, packages/botfuel-dialog/tests/views/intent-resolution-view.test.js, packages/test-complexdialogs/src/views/alcohol-view.en.js, packages/test-complexdialogs/src/views/cancel-view.en.js, packages/test-complexdialogs/src/views/greetings-view.en.js, packages/test-complexdialogs/src/views/question-view.en.js, packages/test-complexentities/src/views/cities-view.js, packages/test-complexentities/src/views/guess-view.js, packages/test-complexentities/src/views/weight-view.js, packages/test-ecommerce/src/views/products-view.en.js, packages/test-ecommerce/src/views/single-product-view.en.js, packages/test-modules/src/dialogs/concrete-dialog.sample-module.js, packages/test-modules/tests/resolutions.test.js, packages/test-qna/src/views/delivery-date-view.js
- BREAKING CHANGE. data will be {entities: ..., somethingelse:...}
- Can impact user dialogs that subclass Dialog
- BREAKING CHANGE: extraData will be merged into data if object, otherwise will be { ...data, extraData} if extraData is value.
=> refactor: replace entities in dialog object by data

packages/botfuel-dialog/package.json, packages/test-complexdialogs/package.json, packages/test-complexentities/package.json, packages/test-ecommerce/package.json, packages/test-middlewares/package.json, packages/test-modules/package.json, packages/test-qna/package.json, packages/test-resolvers/package.json
When `lerna run my_command`where `my_command: "command1; command2"`, only `command2` gets checked for non-zero status code.
For example: `"style": "eslint src; eslint tests",` lints only for tests...
=> fix: Fix lerna run style

.prettierrc, package.json, packages/botfuel-dialog/package.json, yarn.lock
See https://app.asana.com/0/370953015396593/639638765947418
Husky was used to trigger lint-staged on git precommit hook. lint-staged in turn ran prettier.
We decided to remove it because with eslint on CircleCI, it was no longer necessary. Furthermore, it prevented staging only part of a file. And in some cases it added some style errors instead of removing them, eg:
```
function foo(param) { // eslint-disable-line no-unused-vars
}
```
becomes
```
function foo(param) {
// eslint-disable-line no-unused-vars
}
```
=> Remove prettier on eslint

codecov.yml, packages/botfuel-dialog/package.json, packages/botfuel-dialog/src/adapters/messenger-adapter.js, packages/botfuel-dialog/src/adapters/web-adapter.js, packages/botfuel-dialog/src/messages/bot-text-message.js, packages/botfuel-dialog/src/messages/message.js, packages/botfuel-dialog/src/messages/quickreplies-message.js, packages/botfuel-dialog/tests/adapters/messenger-adapter.test.js, packages/test-qna/package.json, yarn.lock
Connected to https://app.asana.com/0/481142309329793/660479534899917
Because we were all ashamed of the poor coverage of the `MessengerAdapter`. The testing is not perfect yet (only the messenger adapter, one very big test) but as Martin Fowler says, an imperfect test suite is better than no test.
This PR introduces the following changes:
* dev dependency on `sinon` is put in the root `package.json`
* `MessengerAdapter.handleRequest` sends a response 200 and returns *after* all the events have been processed. See https://github.com/Botfuel/botfuel-dialog/pull/177/files#diff-e275d0323410e4245b0dde03c9bac553R112 This is better for testing.
* It took me some time to add the flow annotation but it exposed a bug that is fixed here: https://github.com/Botfuel/botfuel-dialog/pull/177/files#diff-e …
=> Test Messenger Adapters

packages/botfuel-dialog/src/corpora/corpus.js, packages/botfuel-dialog/src/corpora/file-corpus.js, packages/botfuel-dialog/tests/corpora/corpus.test.js, packages/botfuel-dialog/tests/corpora/file-corpus.test.js, packages/botfuel-dialog/tests/corpora/test-corpus,comma.txt, packages/botfuel-dialog/tests/corpora/test-corpus-comma.txt, packages/botfuel-dialog/tests/corpora/test-corpus-much-comma.txt
fix corpus comma error. When we have a error format, return ExtractorError
task Asana : https://app.asana.com/0/481142309329793/670660760628697
=> fix: add manage error comma in Corpus

packages/botfuel-dialog/src/views/classification-disambiguation-view.js, packages/botfuel-dialog/tests/views/classification-disambiguation-view.test.js
When we had disambiguation view, the bot crash before we hadn't payload.option
Now, the bot display choice in messenger when we have a disambiguation
task Asana: https://app.asana.com/0/481142309329793/693136421889456
=> fix: fix messenger bot when we have disambiguation view

packages/botfuel-dialog/src/nlus/botfuel-nlu.js
See https://app.asana.com/0/370953015396593/736287362900672
=> fix: Do not log unloggable context

packages/botfuel-dialog/src/brains/brain.js, packages/botfuel-dialog/src/brains/memory-brain.js, packages/botfuel-dialog/src/brains/mongo-brain.js, packages/botfuel-dialog/tests/adapters/adapter.test.js, packages/botfuel-dialog/tests/adapters/test-adapter.test.js, packages/botfuel-dialog/tests/brains/brains.test.js, packages/botfuel-dialog/tests/dialogs/prompt-dialog.test.js, packages/test-complexdialogs/tests/disgressions.test.js, packages/test-complexdialogs/tests/name.test.js, packages/test-complexdialogs/tests/travel.test.js, packages/test-complexentities/tests/cities.test.js, packages/test-complexentities/tests/guess.test.js
The problem was about the ambiguity of the 'getLastConversation' method's name since traditionally a getter method doesn't alter the state of an object.
The name was changed to 'lastConversation' and a line in the doc was added to explain what happens if the last conversation isn't valid anymore.
=> changed name of getLastConversation for lastConversation

packages/botfuel-dialog/src/extractors/ws-extractor.js
In the [WsExtractor](https://github.com/Botfuel/botfuel-dialog/blob/master/packages/botfuel-dialog/src/extractors/ws-extractor.js), retry to request the service if the request fail with a 503 http status code.
Related issue https://github.com/Botfuel/botfuel-dialog/issues/231
=> Retry entity extraction request 3 times if 503 error

fixtures/api.botfuel.io-443/153683284708943108, fixtures/api.botfuel.io-443/153683284750164752, fixtures/api.botfuel.io-443/153683284770384882, fixtures/api.botfuel.io-443/153683284786511736, fixtures/api.botfuel.io-443/153683284804994737, fixtures/api.botfuel.io-443/153683284831572152, fixtures/api.botfuel.io-443/153691324381679185, fixtures/api.botfuel.io-443/153691324429584252, fixtures/api.botfuel.io-443/153691324466980541, fixtures/api.botfuel.io-443/153691324503565521, fixtures/api.botfuel.io-443/153691324566963658, fixtures/api.botfuel.io-443/15369132462794822, packages/botfuel-dialog/src/dialog-manager.js, packages/test-complexdialogs/tests/travel.test.js
With this PR the bot will trigger the **default-dialog** when the user trigger the same intent twice without new entities extracted the second time
Let's see an example with an intent **Travel** with two entity: a **date** and a **city**.
```
U: I want to travel tomorrow
B: Where ?
U: I want to travel // here the user trigger the same intent, without any entity
B: Not understood. // the bot don't ask for the city entity another time
U: Where ?
```
Related issue https://github.com/Botfuel/botfuel-dialog/issues/237
=> Trigger default dialog when the same dialog is triggered twice without extra entity the second time

fixtures/api.botfuel.io-443/153719099235662863, fixtures/api.botfuel.io-443/153719099305590782, fixtures/api.botfuel.io-443/153719099363180620, fixtures/api.botfuel.io-443/153719099382623583, packages/botfuel-dialog/src/bot.js, packages/botfuel-dialog/src/dialog-manager.js, packages/botfuel-dialog/src/dialogs/dialog.js, packages/botfuel-dialog/src/types.js, packages/botfuel-dialog/tests/dialogs/dialog.test.js, packages/botfuel-dialog/tests/views/qnas-view.test.js, packages/test-complexdialogs/tests/alcohol.test.js, packages/test-complexdialogs/tests/blank.test.js, packages/test-complexdialogs/tests/chaining.test.js, packages/test-complexdialogs/tests/greetings.test.js, packages/test-ecommerce/tests/products.test.js
Added `triggeredBy` property to dialogs.
This property can be one of the following:
- **nlu**: the dialog has been triggered by the classification results
- **dialog-manager**: the dialog has been triggered by the dialog manager, this may happen when there is no classification results (default dialog triggered), when there is too much classification results (classification-disambiguation dialog triggered) or when a confirmation is required to continue a dialog (confirmation-dialog)
- **postback**: the dialog has been triggered by the click on a postback button
- **<DIALOG_NAME>-dialog**: the dialog has been triggered by another dialog (using triggerNext or cancelPrevious or startNewConversation when the next dialog name is provided)
=> Add triggeredBy property to dialogs

packages/botfuel-dialog/src/bot.js, packages/botfuel-dialog/tests/messages/postback-message.test.js
Before only `messageEntities` where passed to the dialog data, now we allow custom keys.
=> Allow custom data in Postback messages

packages/botfuel-dialog/src/adapters/botfuel-adapter.js
In the Botfuel adapter, new messages are now handled by building a `UserMessage` instead of sending the request body to the bot.
These messages have now a `options.origin` property which have the following format:
```javascript
...
payload: {
value: <value>
options: {
origin: {
platform: 'Botfuel Webchat',
referrer: <the_referrer_url>
}
}
}
...
```
=> feat: handle UserMessage with origin option in botfuel-adapter

packages/botfuel-dialog/src/extractors/composite-extractor.js
Improve `CompositeExtractor` by executing extractors `compute()` async method in parallel.
Benchmarked with 8 corpus extractors, 4 web service extractors, 1 RegExp extractor and 1 custom extractor, the previous way took 1113.778ms. The new way took 457.293ms.
=> perf: run compute functions in parallel into CompositeExtractor

packages/botfuel-dialog/src/dialog-manager.js
Add QnAs label into ClassificationResults to be able to retreived it into the bot, for example into out middleware to send it to analytics tool.
=> feat: Add QnAs label into ClassificationResults

packages/botfuel-dialog/src/adapters/web-adapter.js
Prevent error due to missing main layout for handlebars, required after express@>=4.0.0
=> Fix template route
